export const technologies = [
  {
    id: '01',
    text: 'HTML',
  },
  {
    id: '02',
    text: 'CSS',
  },
  {
    id: '03',
    text: 'JS',
  },
  {
    id: '04',
    text: 'React',
  },
  {
    id: '05',
    text: 'Git',
  },
  {
    id: '06',
    text: 'Express.js',
  },
  {
    id: '07',
    text: 'mongoDB',
  },
];

export const movies = [
  {
    country: "США",
    director: "Антуан Фукуа",
    duration: "2ч 0м",
    year: "2013",
    description: "Когда на Белый Дом нападают террористы, а президента берут в заложники, дискредитированный бывший охранник главы государства Майк Бэннинг оказывается внутри захваченного здания. И теперь он единственный, кто сможет спасти президента…",
    image: "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/647c4b08-6e64-402c-bda2-5d45251608b9/1920x",
    trailer: "https://www.kinopoisk.ru/film/673427/video/75230/",
    thumbnail: "https://www.kinopoisk.ru/film/673427/video/75230/",
    movieId: 1,
    nameRU: "Падение Олимпа",
    nameEN: "Olympus Has Falle",
  },
  {
    country: "США",
    director: "Антуан Фукуа",
    duration: "2ч 0м",
    year: "2013",
    description: "Когда на Белый Дом нападают террористы, а президента берут в заложники, дискредитированный бывший охранник главы государства Майк Бэннинг оказывается внутри захваченного здания. И теперь он единственный, кто сможет спасти президента…",
    image: "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/647c4b08-6e64-402c-bda2-5d45251608b9/1920x",
    trailer: "https://www.kinopoisk.ru/film/673427/video/75230/",
    thumbnail: "https://www.kinopoisk.ru/film/673427/video/75230/",
    movieId: 2,
    nameRU: "Падение Олимпа",
    nameEN: "Olympus Has Falle",
  },
  {
    country: "США",
    director: "Антуан Фукуа",
    duration: "2ч 0м",
    year: "2013",
    description: "Когда на Белый Дом нападают террористы, а президента берут в заложники, дискредитированный бывший охранник главы государства Майк Бэннинг оказывается внутри захваченного здания. И теперь он единственный, кто сможет спасти президента…",
    image: "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/647c4b08-6e64-402c-bda2-5d45251608b9/1920x",
    trailer: "https://www.kinopoisk.ru/film/673427/video/75230/",
    thumbnail: "https://www.kinopoisk.ru/film/673427/video/75230/",
    movieId: 3,
    nameRU: "Падение Олимпа",
    nameEN: "Olympus Has Falle",
  },
  {
    country: "США",
    director: "Антуан Фукуа",
    duration: "2ч 0м",
    year: "2013",
    description: "Когда на Белый Дом нападают террористы, а президента берут в заложники, дискредитированный бывший охранник главы государства Майк Бэннинг оказывается внутри захваченного здания. И теперь он единственный, кто сможет спасти президента…",
    image: "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/647c4b08-6e64-402c-bda2-5d45251608b9/1920x",
    trailer: "https://www.kinopoisk.ru/film/673427/video/75230/",
    thumbnail: "https://www.kinopoisk.ru/film/673427/video/75230/",
    movieId: 4,
    nameRU: "Падение Олимпа",
    nameEN: "Olympus Has Falle",
  },
  {
    country: "США",
    director: "Антуан Фукуа",
    duration: "2ч 0м",
    year: "2013",
    description: "Когда на Белый Дом нападают террористы, а президента берут в заложники, дискредитированный бывший охранник главы государства Майк Бэннинг оказывается внутри захваченного здания. И теперь он единственный, кто сможет спасти президента…",
    image: "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/647c4b08-6e64-402c-bda2-5d45251608b9/1920x",
    trailer: "https://www.kinopoisk.ru/film/673427/video/75230/",
    thumbnail: "https://www.kinopoisk.ru/film/673427/video/75230/",
    movieId: 5,
    nameRU: "Падение Олимпа",
    nameEN: "Olympus Has Falle",
  },
  {
    country: "США",
    director: "Антуан Фукуа",
    duration: "2ч 0м",
    year: "2013",
    description: "Когда на Белый Дом нападают террористы, а президента берут в заложники, дискредитированный бывший охранник главы государства Майк Бэннинг оказывается внутри захваченного здания. И теперь он единственный, кто сможет спасти президента…",
    image: "https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/647c4b08-6e64-402c-bda2-5d45251608b9/1920x",
    trailer: "https://www.kinopoisk.ru/film/673427/video/75230/",
    thumbnail: "https://www.kinopoisk.ru/film/673427/video/75230/",
    movieId: 6,
    nameRU: "Падение Олимпа",
    nameEN: "Olympus Has Falle",
  },
];

export const navTabLinksConfig = [
  {
    id: 1,
    link: '#о_проекте',
    text: 'О проекте',
  },
  {
    id: 2,
    link: '#технологии',
    text: 'Технологии',
  },
  {
    id: 3,
    link: '#студент',
    text: 'Студент',
  },
]
